# Generated by Django 4.0.5 on 2022-07-03 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autho_parks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('year', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('autho_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='autho_parks.authoparkmodel')),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
