# Generated by Django 4.0.5 on 2022-06-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='computermodel',
            table='computers',
        ),
    ]
