# Generated by Django 4.0.5 on 2022-06-25 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0002_alter_computermodel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computermodel',
            options={'verbose_name': 'Computer'},
        ),
    ]
